
image: jdrouet/docker-with-buildx:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker pull $CI_REGISTRY_IMAGE${tag} || true
    - docker build -t $CI_REGISTRY_IMAGE${tag} .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
#    - docker buildx create --use
#    - docker build . && docker buildx build  --platform linux/arm64/v8,linux/amd64,linux/386,linux/arm/v7 --cache-from type=registry,ref=$CI_REGISTRY_IMAGE:buildcache  --cache-to type=registry,ref=$CI_REGISTRY_IMAGE:buildcache --tag $CI_REGISTRY_IMAGE${tag}  . 


#    - docker pull ${REGISTRY_PROJECT}/${PROJECT_NAME}:latest
#    - docker login  -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
#    - docker build . && docker buildx build  --platform linux/arm64/v8,linux/amd64,linux/386,linux/arm/v7 --cache-from type=registry,ref=$CI_REGISTRY_IMAGE:cache  --tag ${REGISTRY_PROJECT}/${PROJECT_NAME}:latest  . 

## --cache-from type=registry,ref=${REGISTRY_PROJECT}/${PROJECT_NAME}:buildcache --cache-to type=registry,ref=${REGISTRY_PROJECT}/${PROJECT_NAME}:buildcache 
## --cache-from type=registry,ref=$CI_REGISTRY_IMAGE:cache --cache-to type=registry,ref=$CI_REGISTRY_IMAGE:cache

## 

  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
